# Generated by Django 4.2.4 on 2023-08-31 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('condition', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('carbon_monoxide', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ozone', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nitrogen_dioxide', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sulphur_dioxide', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pm2_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pm10', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('us_epa_index', models.IntegerField()),
                ('gb_defra_index', models.IntegerField()),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
