# Generated by Django 4.2.4 on 2023-08-20 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='latitude',
            new_name='wind_speed',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='longitude',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('carbon_monoxide', models.FloatField()),
                ('ozone', models.FloatField()),
                ('nitrogen_dioxide', models.FloatField()),
                ('sulphur_dioxide', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('us_epa_index', models.IntegerField()),
                ('gb_defra_index', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
