# Generated by Django 4.2.4 on 2023-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_airquality_city_weatherdata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
